# Generated by Django 5.0.6 on 2024-05-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=55)),
                ('Book_Id', models.IntegerField()),
                ('Book_Author', models.CharField(max_length=55)),
            ],
            options={
                'db_table': 'bookslist',
            },
        ),
    ]
